import type { Metadata } from 'next';
import '../styles/globals.css';

import MarkPro from 'next/font/local';
const markpro = MarkPro({
  src: [
    {
      path: '../public/fonts/MarkPro-Black.woff2',
      weight: '700',
      style: 'normal',
    },
    {
      path: '../public/fonts/MarkPro-Heavy.woff2',
      weight: '600',
      style: 'normal',
    },
    {
      path: '../public/fonts/MarkPro-Medium.woff2',
      weight: '500',
      style: 'normal',
    },
    {
      path: '../public/fonts/MarkPro-Regular.woff2',
      weight: '400',
      style: 'normal',
    },
    {
      path: '../public/fonts/MarkPro-Light.woff2',
      weight: '300',
      style: 'normal',
    },
    {
      path: '../public/fonts/JetBrainsMono-Thin.woff2',
      weight: '200',
      style: 'normal',
    },
  ],
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={markpro.className}>{children}</body>
    </html>
  );
}
